name: trackit_color
description: Trackit logger extension for color formatting logs to the console.
version: 0.0.1+1
repository: https://github.com/unger1984/trackit

topics:
  - logger
  - logging
  - log
  - console
  - cli

environment:
  sdk: ">2.19.0 <3.6.0"

dependencies:
  ansicolor: ^2.0.3
  trackit: ^0.0.1+1

dev_dependencies:
  lints: ^5.0.0
  test: ^1.25.8
