name: Trackit
repository: https://github.com/unger1984/trackit

sdkPath: .fvm/flutter_sdk

packages:
 - packages/*

command:
 bootstrap:
  usePubspecOverrides: true
  dependencies:
   meta: ^1.15.0
 version:
  # Only allow versioning to happen on main branch.
  branch: main
  # Generates a link to a prefilled GitHub release creation page.
  releaseUrl: true

scripts:
 lint:all:
  steps:
   - analyze
   - format
  description: Run all static analysis checks.
 test:
  run: dart run melos exec --dir-exists=test -- "flutter test --coverage"
  description: Run tests for all packages